"""added ipaddr field

Revision ID: 5f224d19728f
Revises: ff2309d90654
Create Date: 2019-06-23 17:15:05.501012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f224d19728f'
down_revision = 'ff2309d90654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_query', sa.Column('ipaddr', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_query', 'ipaddr')
    # ### end Alembic commands ###
